window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t451_initMenu(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;t_onFuncLoad('t_menuWidgets__init',function(){t_menuWidgets__init(recId)});var burgerList=rec.querySelectorAll('.t451 .t-menuburger');var menu=rec.querySelector('.t451m');var menuBlock=rec.querySelector('.t451');var overlay=rec.querySelector('.t451m__overlay');Array.prototype.forEach.call(burgerList,function(burger){burger.addEventListener('click',function(e){e.preventDefault();t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu)})});if(menu){menu.click(function(e){t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu);e.preventDefault()})}
if(menuBlock){menuBlock.addEventListener('clickedAnchorInTooltipMenu',function(){t451_closeMenu(menu,overlay)})}
rec.addEventListener('click',function(e){if(window.innerWidth>980)return;var submenuClassList=['.t451__link-item_submenu','.t966__tm-link','.t978__tm-link','.t978__menu-link_hook',];var isContainsSubmenuClass=submenuClassList.some(function(className){return e.target.closest(className)});if(!isContainsSubmenuClass)return;setTimeout(function(){t451_checkSize(menu)},100)});window.addEventListener('resize',function(){t451_checkSize(menu)});menu.addEventListener('menuOverflow',function(){t451_checkSize(menu)});var navLinks=rec.querySelectorAll('.t451 a.t-menu__link-item[href*="#"], .t451 a.t-menusub__link-item[href*="#"]');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length>0){t_onFuncLoad('t_menu__updateActiveLinks',function(){t_menu__updateActiveLinks(navLinks,'.t451')})}
t_onFuncLoad('t_menu__highlightActiveLinks',function(){t_menu__highlightActiveLinks('.t451m__menu a')});document.addEventListener('click',function(e){if(e.target.closest('.t451m__overlay, .t451m__close, a[href*="#"]:not(.tooltipstered):not(.t794__tm-link):not(.t978__tm-link):not(.t966__tm-link):not(.t978__menu-link_hook):not(.t-menuwidgeticons__link_wishlist):not(.t-menuwidgeticons__link_cart)')){t451_closeMenu(menu,overlay)}});document.addEventListener('keydown',function(e){if(e.keyCode===27){t451_closeMenu(menu,overlay)}})}
function t451_showMenu(menu,overlay){if(!menu)return;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t451__body_menushowed');menu.classList.add('t451m__menu_show');if(overlay)overlay.classList.add('t451m__menu_show')}
function t451_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t451__body_menushowed');if(menu)menu.classList.remove('t451m__menu_show');if(overlay)overlay.classList.remove('t451m__menu_show')}
function t451_checkSize(menu){if(!menu)return;var menuTop=menu.querySelector('.t451m__top');var menuRight=menu.querySelector('.t451m__rightside');var menuContainer=menu.querySelector('.t451m__container');var menuTopHeight=menuTop?menuTop.offsetHeight:0;var menuRightHeight=menuRight?menuRight.offsetHeight:0;var windowPadding=80;if(menuTopHeight+menuRightHeight+windowPadding>window.innerHeight){menu.classList.add('t451m__overflowed');if(menuContainer)menuContainer.style.height='auto'}else{menu.classList.remove('t451m__overflowed');if(menuContainer)menuContainer.style.height=''}}
function t451_appearMenu(recId){var rec=document.getElementById('rec'+recId);var burger=rec?rec.querySelector('.t451__panel'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';if(burgerAppearOffset)burgerAppearOffset=t451_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t451__beforeready')){burger.classList.remove('t451__beforeready')}}else{burger.classList.add('t451__beforeready')}}
function t451_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor(window.innerHeight*(parseInt(string,10)/100))}
return parseInt(string,10)}
var t776_POPUP_SHOWED_EVENT_NAME='catalog:popupShowed';var t776_POPUP_CLOSED_EVENT_NAME='catalog:popupClosed';function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t776_initProductQuantity(recid)});var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)},500)}
function t776_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t776__col, .t776__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t776__showMore(recid){var rec=document.querySelector('#rec'+recid+' .t776');if(!rec)return;var cardsCount=parseInt(rec.getAttribute('data-show-count'),10);if(isNaN(cardsCount)||cardsCount<1)return;var showMoreButton=rec.querySelector('.t776__showmore');if(!showMoreButton)return;const showMoreTextContainer=showMoreButton.querySelector('.js-btn-txt');if(showMoreTextContainer){showMoreTextContainer.textContent=t776__dict()}
var firstProductCard=rec.querySelector('.t776__col');if(!firstProductCard)return;var productCards=rec.querySelectorAll('.t776__col');var cardsLenght=productCards.length;if(!window.getComputedStyle)return;if(cardsLenght>cardsCount){showMoreButton.style.removeProperty('display')}
Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});t776__showSeparator(rec,cardsCount);for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}
window.addEventListener('resize',function(){Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}});var showedCardsCount=0;showMoreButton.addEventListener('click',function(){Array.prototype.forEach.call(productCards,function(product){if(product.style.display===''){showedCardsCount++}});cardsCount+=showedCardsCount;for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}
if(cardsCount>=cardsLenght){showMoreButton.style.display='none'}
t776__showSeparator(rec,cardsCount);if(rec.querySelector('[data-buttons-v-align]')){t776__alignButtons(recid)}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t776__showSeparator(rec,cardsCount){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t776__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t776__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsCount){separator.classList.remove('t776__separator_hide')}})}
function t776__dict(){var dictionary={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t776__hoverZoom_init(recid){if(window.isMobile){return}
var rec=document.getElementById('rec'+recid);if(!rec)return;var parent=rec.querySelector('.t776__parent');try{if(parent&&parent.getAttribute('data-hover-zoom')!=='yes'){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t776__updateLazyLoad(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var scrollContainer=rec.querySelector(' .t776__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var openerLink=rec.querySelectorAll('[href^="#prodpopup"]');var popup=rec.querySelector('.t-popup');Array.prototype.forEach.call(openerLink,function(link){var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productLinks=document.querySelectorAll('.r a[href$="#!/tproduct/'+recid+'-'+productLid+'"]');Array.prototype.forEach.call(productLinks,function(productLink){productLink.addEventListener('click',function(){if(rec.querySelector('[data-product-lid="'+productLid+'"]')){var linkToPopup=product.querySelector('[href^="#prodpopup"]');if(linkToPopup){var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);linkToPopup.dispatchEvent(event)}}})});link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+productLid+'')});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',showPopupHandler,!1);function showPopupHandler(event){event.preventDefault();if(event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn')){return}
t776_showPopup(recid);var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var allProducts=popup.querySelectorAll('.js-product');Array.prototype.forEach.call(allProducts,function(product){product.style.display='none'});var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');if(productFull){productFull.style.display='block'}
var analitics=popup.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtualTitle=productName.textContent;if(!virtualTitle){virtualTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtualTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')===-1&&currentUrl.indexOf('%23!/tproduct/')===-1){if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t776_updateSlider(recid+' #t776__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}});if(document.querySelectorAll('#record'+recid).length===0){t776_checkUrl(recid)}
if(popup&&popup.hasAttribute('data-fixed-button')){t776_fixedPopupButton(recid)}}
function t776_checkUrl(recid){if(window.catalogUrlProcessed)return;var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}
if(typeof rec.scrollIntoView==='function'){rec.scrollIntoView({block:'start'})}
window.catalogUrlProcessed=!0}}}
function t776_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var position=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*position+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t_triggerEvent(popup,t776_POPUP_SHOWED_EVENT_NAME)},50);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},300);var body=document.body;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t776_closePopup(body,popup)}});var closeButtons=rec.querySelectorAll('.t-popup__close, .t776__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t776_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t776_closePopup(body,popup)}}});if(window.isSafari){setTimeout(function(){popup.scrollTop=1})}}
function t776_closePopup(body,popup){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/')}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',currentUrl)}},300);t_triggerEvent(popup,t776_POPUP_CLOSED_EVENT_NAME)}
function t776_fixedPopupButton(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var MOBILE_MAX_WIDTH=560;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var btnWrappers=rec.querySelectorAll('.t776__btn-wrapper');Array.prototype.forEach.call(btnWrappers,function(el){el.classList.add('t776__btn-wrapper-fixed')});function addStyle(){popupContainer.style.paddingBottom='90px';popupContainer.style.cssText+=';transform:none !important;'}
function resetStyle(){popupContainer.style.paddingBottom='';popupContainer.style.transform=''}
function handleResize(){if(window.innerWidth>MOBILE_MAX_WIDTH){resetStyle();return}
addStyle()}
if(window.isMobile){window.addEventListener('orientationchange',handleResize)}
popup.addEventListener(t776_POPUP_SHOWED_EVENT_NAME,function(){setTimeout(function(){handleResize()})});popup.addEventListener(t776_POPUP_CLOSED_EVENT_NAME,function(){resetStyle()});window.addEventListener('resize',handleResize)}